import type { FcellsContratoRow } from '../repositories/fcellsContratoRepository';
import { parseNetSuiteDate, toStringOrNull } from './utils';

export function mapFcellsContrato(raw: Record<string, any>): FcellsContratoRow {
  return {
    netsuite_id: String(raw.id),
    name: toStringOrNull(raw.name),
    created: toStringOrNull(raw.created),
    lastmodified: toStringOrNull(raw.lastmodified),
    lastmodifieddate_dt: parseNetSuiteDate(raw.lastmodified),
    links: raw.links ? JSON.stringify(raw.links) : null,
    custrecord1404: toStringOrNull(raw.custrecord1404),
    custrecord_cryo_courtesy_created: toStringOrNull(raw.custrecord_cryo_courtesy_created),
    custrecord_cryo_courtesy_year: toStringOrNull(raw.custrecord_cryo_courtesy_year),
    custrecord_cryo_cobradorfcells: toStringOrNull(raw.custrecord_cryo_cobradorfcells),
    custrecord_cryo_estatusfcells: toStringOrNull(raw.custrecord_cryo_estatusfcells),
    custrecord_cryo_fcells_linea_negocio_mue: toStringOrNull(raw.custrecord_cryo_fcells_linea_negocio_mue),
    custrecord_cryo_fcells_mesenquimal: toStringOrNull(raw.custrecord_cryo_fcells_mesenquimal),
    custrecord_cryo_fcells_pagadohasta: toStringOrNull(raw.custrecord_cryo_fcells_pagadohasta),
    custrecord_cryo_fcells_ubicacion_muestra: toStringOrNull(raw.custrecord_cryo_fcells_ubicacion_muestra),
    custrecord_cryo_fcellscorreopaciente: toStringOrNull(raw.custrecord_cryo_fcellscorreopaciente),
    custrecord_cryo_fecha_procesamiento: toStringOrNull(raw.custrecord_cryo_fecha_procesamiento),
    custrecord_cryo_fechaalta: toStringOrNull(raw.custrecord_cryo_fechaalta),
    custrecord_cryo_idexternocontrato: toStringOrNull(raw.custrecord_cryo_idexternocontrato),
    custrecord_cryo_medicotitular: toStringOrNull(raw.custrecord_cryo_medicotitular),
    custrecord_cryo_motivobaja: toStringOrNull(raw.custrecord_cryo_motivobaja),
    custrecord_cryo_muestrafcells: toStringOrNull(raw.custrecord_cryo_muestrafcells),
    custrecord_cryo_owner_muestra: toStringOrNull(raw.custrecord_cryo_owner_muestra),
    custrecord_cryo_pacientefcells: toStringOrNull(raw.custrecord_cryo_pacientefcells),
    custrecord_cryo_productofcells: toStringOrNull(raw.custrecord_cryo_productofcells),
    custrecord_cryo_sales_order_assigned: toStringOrNull(raw.custrecord_cryo_sales_order_assigned),
    custrecord_cryo_sales_order_currency: toStringOrNull(raw.custrecord_cryo_sales_order_currency),
    custrecord_cryo_sales_order_id: toStringOrNull(raw.custrecord_cryo_sales_order_id),
    custrecord_cryo_sales_order_subsidiary: toStringOrNull(raw.custrecord_cryo_sales_order_subsidiary),
    custrecord_cryo_subsidiariafcells: toStringOrNull(raw.custrecord_cryo_subsidiariafcells),
    custrecord_cryo_vendedorfcells: toStringOrNull(raw.custrecord_cryo_vendedorfcells),
    custrecord_cryo_year_charge_annuality: toStringOrNull(raw.custrecord_cryo_year_charge_annuality),
    externalid: toStringOrNull(raw.externalid),
    isinactive: toStringOrNull(raw.isinactive),
    lastmodifiedby: toStringOrNull(raw.lastmodifiedby),
    owner: toStringOrNull(raw.owner),
    scriptid: toStringOrNull(raw.scriptid),
    raw_data: JSON.stringify(raw),
  };
}
